version: '2'
services:
    jhng20180920-mongodb:
        image: mongo:3.6.3
        ports:
            - "27017:27017"
        command: mongos --configdb jhng20180920-mongodb-config
    jhng20180920-mongodb-node:
        build:
            context: .
            dockerfile: mongodb/MongoDB.Dockerfile
        command: mongod --replSet rs1 --noprealloc --smallfiles
    jhng20180920-mongodb-config:
        image: mongo:3.6.3
        container_name: jhng20180920-mongodb-config
        command: mongod --noprealloc --smallfiles --configsvr --dbpath /data/db
