version: '2'
services:
    jhng20180920-mongodb:
        image: mongo:3.6.3
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/jhng20180920/mongodb/:/data/db/
